name: "Grid Virtual Storage"
description: "Emulation of prosument virtual energy storage that is legacy offer for Polish citizens for connecting photovoltaics to the grid"
version: "0.0.1-SNAPSHOT"
slug: "grid-virtual-storage"
init: false
arch:
  - amd64
startup: services
panel_icon: "mdi:transmission-tower-import"
panel_admin: true
panel_title: "Grid Virtual Storage"
webui: "http://[HOST]:[PORT:8080]"
ports:
  8080/tcp: 8080
legacy: true
ingress: true
ingress_port: 8080
homeassistant_api: true
options:
  mqtt_server_url:
    required: true
    description: "URL of the MQTT server"
    default: "mqtt://localhost:1883"
  mqtt_username:
    required: false
    description: "MQTT server username"
    default: "your_username"
  mqtt_password:
    required: false
    description: "MQTT server password"
    default: "your_password"
  forward_energy_topic:
    required: true
    description: "Topic name for forward energy"
    default: "energy/forward"
  reverse_energy_topic:
    required: true
    description: "Topic name for reverse energy"
    default: "energy/reverse"
