name: "Grid Virtual Storage"
description: "Emulation of prosument virtual energy storage that is legacy offer for Polish citizens for connecting photovoltaics to the grid"
version: "0.0.10.1"
slug: "grid-virtual-storage"
init: false
arch:
  - amd64
  - aarch64
startup: services
panel_icon: "mdi:transmission-tower-import"
panel_admin: true
panel_title: "Grid Virtual Storage"
webui: "http://[HOST]:[PORT:8080]"
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 8080
homeassistant_api: true
options:
  mqttServerUrl: "tcp://localhost"
  mqttUsername: "username"
  mqttPassword: "password"
  forwardEnergyTopic: "/some/topic"
  reverseEnergyTopic: "/some/topic"
  periodicalBalancing: true
  periodicalFlushCron: "58 59 * * * *"
schema:
  mqttServerUrl: "str?"
  mqttUsername: "str?"
  mqttPassword: "str?"
  forwardEnergyTopic: "str?"
  reverseEnergyTopic: "str?"
  periodicalBalancing: "bool"
  periodicalFlushCron: "str?"
